/**
 * API
 * API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaginatedResponseDto { 
    data: Array<string>;
    totalCount: number;
    offset: number;
    limit: number;
}

